---
title: "Agglomerative Hierarchical Clustering"
author: "Joe Walderman"
date: "3/4/2021"
output: 
  html_document:
    theme: lumen
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(here)
library(janitor)
library(naniar)

# Packages for cluster analysis
library(cluster)
library(NbClust)
library(factoextra)
library(dendextend)
library(ggdendro)
```

```{r}
stream <- read_csv(here("data", "steam_chemistry.csv")) %>% 
  clean_names()

stream[stream == -999.0] <- NA # replacing -999 values with NA

avg_site <- stream %>%
  rowwise() %>% 
  mutate(summary = mean(c_across(nh4_u_m:spec_cond_u_spercm), na.rm = TRUE)) %>% 
  select(site_code, summary) %>% 
  group_by(site_code) %>% 
  summarize(mean = mean(summary))

stream_scaled <- avg_site %>% 
  select(mean) %>% 
  scale()

# Add site code rownames to scaled dataset
rownames(stream_scaled) <- avg_site$site_code

# Calculate euclidean distance
euc_distance <- dist(stream_scaled, method = "euclidean")

# Hierarchical clustering with complete linkage
hc_complete <- hclust(euc_distance, method = "complete")

# Base plot
# plot(hc_complete, cex = 0.6, hang = -1)
```

### Dendrogram from Stream Site Cluster Analysis
```{r, fig.align='center'}
ggdendrogram(hc_complete,
             rotate = TRUE) +
  theme_minimal() +
  labs(x = "Site",
       y = " ",
       title = "Multivariate Clustering of Stream Chemistry")
```

**Figure 1** Dendrogram of stream chemistry for sites in the Santa Barbara coastal drainage area. Agglomerative hierarchical clustering with complete linkage was used for this analysis.

### Citation: 
[Santa Barbara Coastal LTER and J. Melack. 2019. SBC LTER: Land: Stream chemistry in the Santa Barbara Coastal drainage area, ongoing since 2000 ver 16. Environmental Data Initiative.](https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-sbc.6.16)
